name: Linter

on:
  push:
    branches:
      - main
      - "v*" # This triggers the workflow for pushes to main and version branches
  pull_request:
    branches:
      - main
      - "v*" # ... and for pull requests to main and version branches.

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
